project:
  type: website

output-dir: docs

website:
  title: "Nduka"
  open-graph: true
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Data Viz
        href: dashboard.qmd
      - text: Blog
        menu:
          - text: RCT
            href: RCTs.qmd
          - text: Regression
            href: Regression.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    mainfont: serif
    fontsize: 18px
    linkcolor: black
    backgroundcolor: "#D3D3D3"
    fontcolor: black
